// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtl9XmFmRU59M_912c690mU0C_brF-WbA',
    appId: '1:506442149894:web:5fab5a6cda5565ed979387',
    messagingSenderId: '506442149894',
    projectId: 'nationallibrarysystemevil',
    authDomain: 'nationallibrarysystemevil.firebaseapp.com',
    storageBucket: 'nationallibrarysystemevil.appspot.com',
    measurementId: 'G-1N7NRFGEWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk1PF_sCpmCJCQ0IK9PxzHK6gsIFNUClc',
    appId: '1:506442149894:android:bb6ac301fe1b79e0979387',
    messagingSenderId: '506442149894',
    projectId: 'nationallibrarysystemevil',
    storageBucket: 'nationallibrarysystemevil.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlxZN8Q39VGyxJg3ZXCm_OVSH48uhUQhE',
    appId: '1:506442149894:ios:35fbfadce006921c979387',
    messagingSenderId: '506442149894',
    projectId: 'nationallibrarysystemevil',
    storageBucket: 'nationallibrarysystemevil.appspot.com',
    iosClientId: '506442149894-v6jaev3a7vifhjbkia42j6d5ug4qrmc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.nationalLibrarySystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlxZN8Q39VGyxJg3ZXCm_OVSH48uhUQhE',
    appId: '1:506442149894:ios:35fbfadce006921c979387',
    messagingSenderId: '506442149894',
    projectId: 'nationallibrarysystemevil',
    storageBucket: 'nationallibrarysystemevil.appspot.com',
    iosClientId: '506442149894-v6jaev3a7vifhjbkia42j6d5ug4qrmc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.nationalLibrarySystem',
  );
}
